/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccordionItem: typeof import('./components/AccordionItem.vue')['default']
    Button: typeof import('./components/Button.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    FlashMessage: typeof import('./components/FlashMessage.vue')['default']
    Loading: typeof import('./components/Loading.vue')['default']
    Modal: typeof import('./components/Modal.vue')['default']
    Radio: typeof import('./components/Radio.vue')['default']
    RequireLabel: typeof import('./components/RequireLabel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollToTopButton: typeof import('./components/ScrollToTopButton.vue')['default']
    SingerButtonList: typeof import('./components/SingerButtonList.vue')['default']
    SingerSongAccordionList: typeof import('./components/SingerSongAccordionList.vue')['default']
    SingersSongList: typeof import('./components/SingersSongList.vue')['default']
    SingersSongs: typeof import('./components/SingersSongs.vue')['default']
    SlideContents: typeof import('./components/SlideContents.vue')['default']
    SongForm: typeof import('./components/SongForm.vue')['default']
    YoutubeThumbnail: typeof import('./components/YoutubeThumbnail.vue')['default']
  }
}
